services:
    min_app.service.compute:
        class: MIN\AppBundle\Service\ComputeService

    min_app.service.function:
        class: MIN\AppBundle\Service\FunctionService
        arguments: ["@min_app.service.compute"]

    min_app.model.solver.hill_climbing:
        class: MIN\AppBundle\Model\Solver\HillClimbingSolver

    min_app.model.solver.genetic:
        class: MIN\AppBundle\Model\Genetic\GeneticSolver
